package guide;

class Top {
	/**
	The implied super() call in Bottom2’s constructor cannot be satisfied because
	there isn’t a no-arg constructor in Top. A default, no-arg constructor is generated by the
	compiler only if the class has no constructor defined explicitly.*/
	public Top() {}
	
	
	public Top(String s) { 
		System.out.print("B"); 
	}
}
public class Bottom2 extends Top {
	
	/**
	 * error if no Top()
	 * @param s
	 */
	public Bottom2(String s) { 
		System.out.print("D"); 
	}

	public static void main(String [] args) {
		new Bottom2("C");
		System.out.println(" ");
	}
}